In [1]:
print('Hello world')

Hello world


### Practice python 

In [3]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [4]:
import numpy as np
np.__version__

'1.21.2'

In [5]:
c=np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [6]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
l=[i**2 for i in a]
l

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [8]:
s='hello'
'-'.join(s)
s

'hello'

In [11]:
s='_'.join(s)
s

'h_______e_______l_______l_______o'

In [13]:
s=' '.join(s)
s

'h _ _ _ _ _ _ _ e _ _ _ _ _ _ _ l _ _ _ _ _ _ _ l _ _ _ _ _ _ _ o'

In [21]:
s='hello'
s=s.split(' ')
s

['hello']

In [27]:
s='1 2 3 4'
nums=map(int,s.split())
print(*nums)
for i in nums:
    print(type(i))

1 2 3 4


In [28]:
a=12
b=23
c=34
print(a,b,c)

12 23 34


In [29]:
s='repeat'
print(3*s)

repeatrepeatrepeat


In [30]:
name=input('Enter your name: ')
print('Your name is',name)

Enter your name:  Revanth


Your name is Revanth


In [31]:
20+23.8

43.8

In [32]:
12+int('23')

35

In [33]:
print('r' in 'rvr')

True


In [35]:
print('y' not  in 'rvr')

True


In [44]:
x=2
y=3
print(id(x),id(y),x is y)

94268654682784 94268654682816 False


In [45]:
num=int(input("Enter any number: "))
if(num % 2 == 0):
    print("even")
else:
    print('odd')

Enter any number:  6


even


In [47]:
ch=input()
ovals='aeiouAEIOU'
print(ch,'is oval') if ch in ovals else print(ch,'is not oval')

 e


e is oval


In [50]:
n=int(input())
print(n,'is negative') if n<0 else print(n,'is positive')

 45


45 is positive


In [ ]:
a,b,c=int(input("a: ")),int(input("b: ")),int(input("c: "))
if a>b and a>c: print(a)
elif b>c and b>a: print(b)
else: print(c)
print("largest using built in function is: "+str(max(a,b,c)))

a:  4


In [6]:
#leap year
year=int(input())
if((year%4 is 0 and year%100 is not 0) or year%400 is 0): print('leap year')
else: print('not a lepa year')

 1900


not a lepa year


In [11]:
#nth table
n=int(input('enter a number: '))
for i in range(1,11):
    print(n,'x',i,'=',n*i)

enter a number:  5


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [27]:
import numpy as np

In [31]:
a1=np.arange(10,14).reshape(2,2)

In [32]:
print(a1)

[[10 11]
 [12 13]]


In [33]:
a2=np.arange(2,6).reshape(2,2)

In [35]:
a2

array([[2, 3],
       [4, 5]])

In [36]:
a1*a2

array([[20, 33],
       [48, 65]])

In [37]:
a1+a2

array([[12, 14],
       [16, 18]])

In [38]:
a1//a2

array([[5, 3],
       [3, 2]])

In [39]:
a1/a2

array([[5.        , 3.66666667],
       [3.        , 2.6       ]])

In [56]:
np.random.randint(18,20)

18

In [58]:
np.random.random(10)

array([0.41585951, 0.09386397, 0.20975481, 0.11605278, 0.93302448,
       0.30710462, 0.31741665, 0.56659613, 0.54573342, 0.08346826])

In [59]:
np.random.rand(2,4)

array([[0.86148795, 0.57329203, 0.21722101, 0.96394008],
       [0.92730741, 0.90298718, 0.17571502, 0.05623037]])

In [68]:
ar=np.arange(16).reshape(2,8)
d=np.diag(ar)
print(ar)
print(d)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[0 9]


In [93]:
for i in range(8): print(ar[0:i,0:i])

[]
[[0]]
[[0 1]
 [8 9]]
[[ 0  1  2]
 [ 8  9 10]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 8  9 10 11 12]]
[[ 0  1  2  3  4  5]
 [ 8  9 10 11 12 13]]
[[ 0  1  2  3  4  5  6]
 [ 8  9 10 11 12 13 14]]


<h1 style='color:white;font-family:cursive;background-color:red;width:125px;border-radius:5px;text-align:center'>END</h1>