# python
- **numpy** (numerical python)
    - 1d array(vector)
    - 2d array(matrix)
    - above 3d(tensor)
    - *supports zero based indexing*
- **pndas**
- **data visualisation**

In [3]:
import numpy as np
np.__version__

'1.15.1'

In [4]:
#id array(vector)
a=np.array([12,3,4,5])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[12  3  4  5]
<class 'numpy.ndarray'>
1
(4,)


In [5]:
b=np.array([[1,2,3,4],[4,5,6,7]])
print(b)
print(type(b))
print(b.ndim)
print(b.shape)

[[1 2 3 4]
 [4 5 6 7]]
<class 'numpy.ndarray'>
2
(2, 4)


In [6]:
c=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(c)
print(type(c))
print(c.ndim)
print(c.shape)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]
<class 'numpy.ndarray'>
3
(1, 3, 3)


In [8]:
l=np.arange(1000)
%timeit [i**2 for i in l]

164 µs ± 871 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [1]:
l=range(1000)
%timeit [i**2 for i in l]

293 µs ± 2.25 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Comprehensions
- comprehensons in general refers to a short paragraph describing something
- Comprehension means shortening the no. of lines of code
- **syntax**
    - [output input sequence condition_check]
- 2 Comprehensions
    - list, dict comprehensions
    - output input conditions

In [13]:
#prepare  a list of square values of numbers present in range
l=[n**2 for n in range(int(input()),int(input())+1)]
print(l)

10
20
[100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [20]:
#prepare multiplication table using list comprehension
n=int(input())
l=[print(n,'x',i,'=',n*i) for i in range(1,10)]
#print(l)

10
10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90


In [28]:
#prepare a list of characters whose ascii va;lues is even ina string
#s=input()
l=[print(x,end=' ') for x in input() if ord(x)%2 is 0]
#print(l)

helloween
h l l n 

#### Dictionary Comprehension
- **chr(x)**
    - gives charcter equivalent to a ascii number
- **ord('x')**
    - gives decimal equivalent to a character

In [29]:
# prepare a dict of cubic values of no.s
#present in a range
l={x:x**3 for x in range(int(input()))}
print(l)

10
{0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729}


In [41]:
#prepare  char dict of numbers in a given range
#l={print(x,chr(x)) for x in range(33,int(input("Enter a number greater than 33 and less than 126: ")))}
l={x:chr(x) for x in range(33,int(input("Enter a number greater than 33: ")))}
print(l)

Enter a number greater than 33 and less than 126: 57
33 !
34 "
35 #
36 $
37 %
38 &
39 '
40 (
41 )
42 *
43 +
44 ,
45 -
46 .
47 /
48 0
49 1
50 2
51 3
52 4
53 5
54 6
55 7
56 8
Enter a number greater than 33: 57
{33: '!', 34: '"', 35: '#', 36: '$', 37: '%', 38: '&', 39: "'", 40: '(', 41: ')', 42: '*', 43: '+', 44: ',', 45: '-', 46: '.', 47: '/', 48: '0', 49: '1', 50: '2', 51: '3', 52: '4', 53: '5', 54: '6', 55: '7', 56: '8'}


## Data Science
- The study of data is called data science
- the data can be existed in deiffernt forms
    - .txt,.mp3 etc..,
- every row can be considered as sample

### Numpy
- Numpy stands for numerical python
- It is one of the most important and efficient module in data science

In [2]:
import numpy as np
np.__version__

'1.15.1'

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [5]:
#Creating an array from the string
st=np.array(input().split())
print(st)
print(type(st))

i hbk jkh
['i' 'hbk' 'jkh']
<class 'numpy.ndarray'>


In [6]:
n=np.array(range(30,43))
n

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [7]:
n=np.array(range(20,30,4))
n

array([20, 24, 28])

In [8]:
n=np.array((2,3,5,'good'))
n

array(['2', '3', '5', 'good'], dtype='<U11')

In [13]:
#2d array using list of lists
n=np.array([(2,4,56,6),(35,2,435,2)])
print(n)
print(n[1][2])

[[  2   4  56   6]
 [ 35   2 435   2]]
435


### Creating array using arrange
- works like range in python

In [18]:
n=np.arange(10)
n=np.arange(10,40)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [7]:
#aaabbccc
#3a2b3c
st=input()
result=''
for ch in st:
    if ch not in result:
        result+=str(st.count(ch))+ch
print(result)

aaaabbbbbbbxxc
4a7b2x1c


In [17]:
import numpy as np
ar=np.arange(1,25).reshape(8,3)
print(ar)
#print(ar.reshape(6,4))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [22]:
#ar=np.arange(10000).reshape(20,-1)
ar=np.arange(10000).reshape(-1,20)
print(ar)

[[   0    1    2 ...   17   18   19]
 [  20   21   22 ...   37   38   39]
 [  40   41   42 ...   57   58   59]
 ...
 [9940 9941 9942 ... 9957 9958 9959]
 [9960 9961 9962 ... 9977 9978 9979]
 [9980 9981 9982 ... 9997 9998 9999]]


### Random
- random.randint()
- random.random()
- random.rand()
- random.randn()

In [36]:
print(np.random.randint(20))

11


In [43]:
print(np.random.randint(10,20))

16


In [46]:
print(np.random.random(20))

[0.73239936 0.0410986  0.83619628 0.02211438 0.70499208 0.52810615
 0.3808348  0.19956595 0.91417628 0.02218826 0.15792108 0.87216372
 0.908971   0.52643602 0.43369778 0.92375076 0.12490205 0.51780493
 0.58649362 0.81272271]


In [48]:
print(np.random.rand(2,4))

[[0.12010022 0.24216949 0.13113826 0.98777061]
 [0.01446442 0.91708303 0.80050663 0.28105999]]


In [51]:
print(np.linspace(2,6,10))

[2.         2.44444444 2.88888889 3.33333333 3.77777778 4.22222222
 4.66666667 5.11111111 5.55555556 6.        ]


In [53]:
ar=np.arange(9).reshape(3,3)
d=np.diag(ar)
print(ar)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


In [55]:
ar[2,1]

7

In [56]:
ar[0:2,0:1]

array([[0],
       [3]])

In [72]:
print('\U0001F357')

🍗


In [76]:
#Scientific computations
#take teo random arrays and perform all the arthimetic operations
a=np.random.randint(10)
a

6

In [78]:
g=np.vectorize(greater)
g([3,4,5],[8,4,0])

NameError: name 'greater' is not defined

In [79]:
help(np.vectorize)

Help on class vectorize in module numpy.lib.function_base:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns an single or tuple of numpy array as
 |  output. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optiona

### pandas
- panel data
- data is in the form of rowa and columns

In [80]:
import pandas as pd
pd.__version__

'0.23.4'

In [81]:
pd.Series('Iam from rvr'.split())

0     Iam
1    from
2     rvr
dtype: object

In [83]:
pd.Series((34,3,2,'revanth'))


0         34
1          3
2          2
3    revanth
dtype: object

In [85]:
#dict into series
pd.Series({1:'mon',2:'tue',3:'wed'})

1    mon
2    tue
3    wed
dtype: object

In [88]:
a=np.arange(2,10)
s=pd.Series(a)
print(s)

0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int32


In [91]:
s.index=[num for num in range(50,58)]

In [92]:
s

50    2
51    3
52    4
53    5
54    6
55    7
56    8
57    9
dtype: int32

In [95]:
s.index[5]

55

In [96]:
s[55]

7

In [97]:
s[::-1]

57    9
56    8
55    7
54    6
53    5
52    4
51    3
50    2
dtype: int32

In [99]:
s[:5]

50    2
51    3
52    4
53    5
54    6
dtype: int32

###  Data Frames

In [122]:
dic={'names':['rashmi','meghana','Haritha'],'roll':[12,23,45]}
dic2={'names':['ras','megh','Hari'],'roll':[17,25,46]}
df=pd.DataFrame(dic)
df2=pd.DataFrame(dic2)
print(df)

     names  roll
0   rashmi    12
1  meghana    23
2  Haritha    45


In [123]:
df

names  roll
0   rashmi    12
1  meghana    23
2  Haritha    45

In [124]:
#merging two data frames
df.merge(df2)

Empty DataFrame
Columns: [names, roll]
Index: []

In [113]:
pd.concat([df,df2])

names  roll
0   ras    17
1  megh    25
2  Hari    46
0   ras    17
1  megh    25
2  Hari    46

In [115]:
df.sample()

names  roll
1  megh    25

In [116]:
df.head()

names  roll
0   ras    17
1  megh    25
2  Hari    46

In [117]:
df

names  roll
0   ras    17
1  megh    25
2  Hari    46

In [118]:
df.tail()

names  roll
0   ras    17
1  megh    25
2  Hari    46

In [120]:
df=pd.concat([df,df2])

In [121]:
df

names  roll
0   ras    17
1  megh    25
2  Hari    46
0   ras    17
1  megh    25
2  Hari    46